// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {controller} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Task>;

export function CheckCaInstalled():Promise<Record<string, any>>;

export function DeleteTask(arg1:number):Promise<void>;

export function DownloadFfmpeg():Promise<Record<string, boolean>>;

export function GetAllProgress():Promise<Array<controller.ProgressInfo>>;

export function GetConfig():Promise<model.Config>;

export function GetFfmpegStatus():Promise<Record<string, boolean>>;

export function GetTasks(arg1:number):Promise<Array<model.Task>>;

export function PauseTask(arg1:number):Promise<void>;

export function RedownloadTask(arg1:number):Promise<void>;

export function RetryTask(arg1:number):Promise<void>;

export function StartAllTasks():Promise<number>;

export function StartOneTask(arg1:number):Promise<void>;

export function StopAllTasks():Promise<void>;

export function UpdateConfig(arg1:Record<string, any>):Promise<model.Config>;

export function UpdateTask(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<model.Task>;

export function UpdateTaskTitle(arg1:number):Promise<model.Task>;
