// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3, arg4);
}

export function CheckCaInstalled() {
  return window['go']['main']['App']['CheckCaInstalled']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DownloadFfmpeg() {
  return window['go']['main']['App']['DownloadFfmpeg']();
}

export function GetAllProgress() {
  return window['go']['main']['App']['GetAllProgress']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFfmpegStatus() {
  return window['go']['main']['App']['GetFfmpegStatus']();
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function RedownloadTask(arg1) {
  return window['go']['main']['App']['RedownloadTask'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function StartAllTasks() {
  return window['go']['main']['App']['StartAllTasks']();
}

export function StartOneTask(arg1) {
  return window['go']['main']['App']['StartOneTask'](arg1);
}

export function StopAllTasks() {
  return window['go']['main']['App']['StopAllTasks']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateTaskTitle(arg1) {
  return window['go']['main']['App']['UpdateTaskTitle'](arg1);
}
