// Code generated by goctl. DO NOT EDIT.
package types

type TaskCreateRequest struct {
	Name      string `json:"name"`                          // 任务名字
	VideoType string `json:"video_type,options=[mp4,m3u8]"` // 视频类型
	Type      string `json:"type,options=[url,curl]"`       // 任务类型
	Data      string `json:"data"`                          // url 或者 curl
}

type TaskCreateResponse struct {
}

type TaskListRequest struct {
}

type TaskListResponse struct {
	Total int64       `json:"total"`
	List  interface{} `json:"list"`
}

type TaskUpdateRequest struct {
	ID        uint   `json:"id"`
	Name      string `json:"name,optional"`       // 任务名字
	VideoType string `json:"video_type,optional"` // 视频类型
	Type      string `json:"type,optional"`       // 任务类型
	Data      string `json:"data,optional"`       // url 或者 curl
}

type TaskUpdateResponse struct {
}

type TaskDeleteRequest struct {
	ID uint `json:"id"`
}

type TaskDeleteResponse struct {
}

type TaskRunRequest struct {
	Stop bool `form:"stop"`
}

type TaskRunResponse struct {
	Message string `json:"message"`
}

type TaskStatusRequest struct {
}

type TaskStatusResponse struct {
	Status bool `json:"status"` // 执行状态
}
